--- # first play book
- hosts: testing_localhost
  become: yes
  tasks:
    - name: install software
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - nginx
        - postgresql
        - mariadb
- hosts: testing_localhost
  tasks:
    - name: Removing httpd
      yum:
        name: "{{ var1 }}"
        state: absent
    - name: adding httpd
      yum:
        name: "{{ var1 }}"
        state: present
- hosts: testing_localhost
  tasks:
    - name: Installing nginx
      yum:
        name: "{{ var2 }}"
        state: present
